# Generated by Django 3.2.25 on 2024-06-21 17:26

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название категории', max_length=128, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': ('Категория',),
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ColorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите цвет', max_length=128, verbose_name='Цвет товара')),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета товаров',
            },
        ),
        migrations.CreateModel(
            name='LocationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите стрвну', max_length=128, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Название страны',
                'verbose_name_plural': 'Название стран',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название товара', max_length=256, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Добавте уникальную ссылку', max_length=64, unique=True, verbose_name='Ссылка')),
                ('article', models.CharField(help_text='Добавте уникальный артикул товара', max_length=64, unique=True, verbose_name='Артикул товара')),
                ('description', models.TextField(help_text='Добавте описание', verbose_name='Описание')),
                ('volume', models.IntegerField(blank=True, help_text='Укажите объём товара', null=True, verbose_name='Объём товара')),
                ('composition', models.TextField(blank=True, help_text='Укажите состав товара', verbose_name='Состав товара')),
                ('usage', models.TextField(blank=True, help_text='Укажите использование товара', verbose_name='Использование товара')),
                ('image', models.ImageField(help_text='Загрузите изображение товара', upload_to='catalog/', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, help_text='Укажите цену', max_digits=10, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.colorproduct')),
                ('location_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.locationproduct')),
            ],
            options={
                'verbose_name': ('Товар',),
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
