# Generated by Django 3.2.25 on 2024-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_imageproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение товара', upload_to='catalog/<django.db.models.query_utils.DeferredAttribute object at 0x110946b50>', verbose_name='Изображение товара'),
        ),
    ]
