# Generated by Django 3.2.25 on 2024-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_imageproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение товара', upload_to='catalog/<TreeQuerySet [<Category: Гель-Лаки>, <Category: Базы для ногтей>, <Category: Гель Лаки>, <Category: Топы для ногтей>, <Category: Наращивание и моделирование ногтей>, <Category: Акрил-гель>, <Category: Гелевая система>, <Category: Жидкий УФ-гель>, <Category: Сопутствующие средства>, <Category: Типсы и формы>]>', verbose_name='Изображение товара'),
        ),
    ]
