# Generated by Django 3.2.25 on 2024-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_imageproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение товара', upload_to='catalog/', verbose_name='Изображение товара'),
        ),
    ]
