# Generated by Django 3.2.25 on 2024-06-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_imageproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='catalog/'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение товара', upload_to='xc/', verbose_name='Изображение товара'),
        ),
    ]
