# Generated by Django 3.2.25 on 2024-07-03 17:11

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=catalog.models.upload_path_product, verbose_name='Картинка категории'),
        ),
    ]
