# Generated by Django 3.2.25 on 2024-07-05 18:15

import catalog.models
from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=catalog.models.upload_path_product, verbose_name='Фото товара'),
        ),
    ]
